gts3l-common: Build kernel modules into /system/lib instead of /system/vendor/lib
In Andriod 14 QPR3, we get this error message if kernel modules are build
into /system/vendor/lib

make[1]: Leaving directory '/media/l/21/out/target/product/gts3lwifi/obj/KERNEL_OBJ'
make: Leaving directory '/media/l/21/kernel/samsung/msm8996'
Installing Kernel Modules
make: Entering directory '/media/l/21/kernel/samsung/msm8996'
make[1]: Entering directory '/media/l/21/out/target/product/gts3lwifi/obj/KERNEL_OBJ'
  INSTALL block/test-iosched.ko
  INSTALL drivers/char/rdbg.ko
  INSTALL drivers/gator/gator.ko
  INSTALL drivers/input/evbug.ko
  INSTALL drivers/mmc/card/mmc_block_test.ko
  INSTALL drivers/mmc/card/mmc_test.ko
  INSTALL drivers/spi/spidev.ko
  INSTALL net/bridge/br_netfilter.ko
  INSTALL net/ipv4/tcp_htcp.ko
  DEPMOD  3.18.140-awesometic-kernel-v0.13+

[ 97% 147/151] Target system fs image: out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system.
FAILED: out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system.img
/bin/bash -c "(mkdir -p out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/ out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates && rm -rf out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_size=4194304000\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_selinux_fc=out/target/product/gts3lwifi/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"building_system_image=true\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"fs_type=ext4\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"erofs_sparse_flag=-s\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"f2fs_sparse_flag=-S\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"avb_avbtool=avbtool\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"avb_system_hashtree_enable=false\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"avb_system_add_hashtree_footer_args=\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"root_dir=out/target/product/gts3lwifi/root\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (sort -o  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt  out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:\$PATH out/host/linux-x86/bin/build_image --input-directory-filter-file out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/file_list.txt out/target/product/gts3lwifi/system out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system_image_info.txt out/target/product/gts3lwifi/obj/PACKAGING/systemimage_intermediates/system.img out/target/product/gts3lwifi/system || ( mkdir -p \${DIST_DIR}; cp out/target/product/gts3lwifi/installed-files.txt \${DIST_DIR}/installed-files-rescued.txt; exit 1 ) )"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/media/l/21/out/host/linux-x86/bin/build_image/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "build_image.py", line 1042, in <module>
  File "build_image.py", line 1034, in main
  File "build_image.py", line 959, in CopyInputDirectory
FileNotFoundError: [Errno 2] No such file or directory: 'out/target/product/gts3lwifi/system/lib/modules/br_netfilter.ko' -> 'out/target/product/gts3lwifi/tmpr14dvsa6/lib/modules/br_netfilter.ko'
13:59:24 ninja failed with: exit status 1
There was 1 action that completed after the action that failed. See verbose.log.gz for its output.

=== other possible hack ===

The other way "fixing" the above is to copy the
$OUT/system/vendor/lib/modules directory to
$OUT/system/lib/modules